export const INVENTORY_ITEM_DEFS = {
  sunCoins: {
    id: 'sun-coins',
    name: 'Sun Coins',
    type: 'Currency',
    description: 'Spendable village currency earned from dungeon chests and companion arcs.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 0,
  },
  fieldTonic: {
    id: 'field-tonic',
    name: 'Field Tonic',
    type: 'Consumable',
    description: 'Restore a chunk of HP during combat to stabilize a risky run.',
    iconTexture: 'ui-field-tonic-icon',
    combat: {
      usable: true,
      effect: {
        kind: 'heal',
        amount: 12,
      },
    },
  },
  emberTonic: {
    id: 'ember-tonic',
    name: 'Ember Tonic',
    type: 'Consumable',
    description: 'Restores more HP than a field tonic and steadies longer dungeon runs.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 1,
    combat: {
      usable: true,
      effect: {
        kind: 'heal',
        amount: 20,
      },
    },
  },
  guardSalve: {
    id: 'guard-salve',
    name: 'Guard Salve',
    type: 'Consumable',
    description: 'A compact combat salve used when early encounters get messy.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 2,
    combat: {
      usable: true,
      effect: {
        kind: 'heal',
        amount: 9,
      },
    },
  },
  slimeJelly: {
    id: 'slime-jelly',
    name: 'Slime Jelly',
    type: 'Loot',
    description: 'Basic dungeon drop tied to contract turn-ins and early progression loops.',
    iconTexture: 'ui-slime-jelly-icon',
  },
  mossThread: {
    id: 'moss-thread',
    name: 'Moss Thread',
    type: 'Loot',
    description: 'Common soft fiber from living dungeon rooms, useful for small trades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 3,
  },
  crackedFang: {
    id: 'cracked-fang',
    name: 'Cracked Fang',
    type: 'Loot',
    description: 'Common monster salvage that villages will trade for supplies.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 4,
  },
  lanternOil: {
    id: 'lantern-oil',
    name: 'Lantern Oil',
    type: 'Loot',
    description: 'Common expedition stock found in practical dungeon chests.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 5,
  },
  boneCharm: {
    id: 'bone-charm',
    name: 'Bone Charm',
    type: 'Rare Loot',
    description: 'An uncommon charm from deeper rooms, valuable but not tied to one NPC.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 6,
  },
  moonPearl: {
    id: 'moon-pearl',
    name: 'Moon Pearl',
    type: 'Rare Loot',
    description: 'A strange pearl occasionally found in old chest caches.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 7,
  },
  ironOre: {
    id: 'iron-ore',
    name: 'Iron Ore',
    type: 'Upgrade Material',
    description: 'Raw metal stock for future weapon and armor upgrades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 8,
  },
  crystalShard: {
    id: 'crystal-shard',
    name: 'Crystal Shard',
    type: 'Upgrade Material',
    description: 'Dungeon reward material reserved for upgrades, contracts, or unlock costs.',
    iconTexture: 'ui-crystal-shard-icon',
  },
  temperedBloom: {
    id: 'tempered-bloom',
    name: 'Tempered Bloom',
    type: 'Upgrade Material',
    description: 'A resilient flower used by village smiths for guard and HP upgrades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 9,
  },
  echoThread: {
    id: 'echo-thread',
    name: 'Echo Thread',
    type: 'Upgrade Material',
    description: 'Reactive thread that helps bind companion rewards into equipment.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 10,
  },
  ashGlass: {
    id: 'ash-glass',
    name: 'Ash Glass',
    type: 'Upgrade Material',
    description: 'Brittle black glass used for sharp attack upgrades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 11,
  },
  mirrorSigil: {
    id: 'mirror-sigil',
    name: 'Mirror Sigil',
    type: 'NPC Relic',
    description: 'A reflective companion relic that marks progress with the Mirror archetype.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 12,
  },
  enablingRibbon: {
    id: 'enabling-ribbon',
    name: 'Enabling Ribbon',
    type: 'NPC Relic',
    description: 'A companion ribbon that improves the first upgrade loop after a completed arc.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 13,
  },
  honestWhetstone: {
    id: 'honest-whetstone',
    name: 'Honest Whetstone',
    type: 'NPC Relic',
    description: 'A clean-edged upgrade relic suited to straightforward attack growth.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 14,
  },
  opportunistToken: {
    id: 'opportunist-token',
    name: 'Opportunist Token',
    type: 'NPC Relic',
    description: 'A risky trade marker carried by ambitious companions.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 15,
  },
  parasiteNeedle: {
    id: 'parasite-needle',
    name: 'Parasite Needle',
    type: 'NPC Relic',
    description: 'A sharp, uneasy relic that belongs in unusual NPC reward pools.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 16,
  },
  duskLace: {
    id: 'dusk-lace',
    name: 'Dusk Lace',
    type: 'NPC Relic',
    description: 'A rare goth companion material used for high-risk upgrades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 17,
  },
  pactInk: {
    id: 'pact-ink',
    name: 'Pact Ink',
    type: 'NPC Relic',
    description: 'Dark contract ink awarded by companions rather than ordinary chests.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 18,
  },
  riftSpindle: {
    id: 'rift-spindle',
    name: 'Rift Spindle',
    type: 'NPC Relic',
    description: 'A peculiar spindle that converts companion trust into upgrade progress.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 19,
  },
  whisperNail: {
    id: 'whisper-nail',
    name: 'Whisper Nail',
    type: 'NPC Relic',
    description: 'An unusual nail kept by quest-givers who trade in strange leverage.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 20,
  },
  violetLens: {
    id: 'violet-lens',
    name: 'Violet Lens',
    type: 'NPC Relic',
    description: 'A rare lens that makes companion completion rewards feel distinct.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 21,
  },
  hearthBadge: {
    id: 'hearth-badge',
    name: 'Hearth Badge',
    type: 'Upgrade Material',
    description: 'A village-workshop badge used to discount practical upgrades.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 22,
  },
  steelButton: {
    id: 'steel-button',
    name: 'Steel Button',
    type: 'Loot',
    description: 'A sturdy little common find that sells well in town.',
    iconTexture: 'ui-custom-item-icons',
    iconFrame: 23,
  },
};

export function createInventoryEntry(itemDef, quantity) {
  return {
    id: itemDef.id,
    name: itemDef.name,
    type: itemDef.type,
    quantity,
    description: itemDef.description,
    iconFrame: itemDef.iconFrame ?? 0,
    iconTexture: itemDef.iconTexture ?? 'ui-inventory-icons',
    combat: itemDef.combat ?? null,
  };
}
